### ISSUE TITLE
Register project in awesome-sanic

### ISSUE THREAD

**Issue by raphaelauv** [shady-robot/sanic-opentracing#6]
Hey thanks for your job , your project should be part of 

https://github.com/mekicha/awesome-sanic

and maybe even part of sanic core

https://community.sanicframework.org/t/opentracing-instrumentation-for-sanic/312/4

**Comment by Octobug** [comment]
> Hey thanks for your job , your project should be part of
> 
> https://github.com/mekicha/awesome-sanic
> 
> and maybe even part of sanic core
> 
> https://community.sanicframework.org/t/opentracing-instrumentation-for-sanic/312/4

@raphaelauv 
Thank you for reminding us. We will have it done as soon as possible.

@shady-robot will take care of it.
